### ISSUE TITLE
Misleading indentation errors on gcc 11.x

### ISSUE THREAD

**Issue by gmolina-a2e** [dvidelabs/flatcc#183]
Had to suppress that warning to be able to compile.

**Comment by gmolina-a2e** [comment]
This does the trick:
if (NOT (GCC_VERSION VERSION_LESS 11.0))
+               # Disable warning on misleading indentation it become more aggressive in 11.0
+               set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-misleading-indentation")
+       endif()

**Comment by mikkelfj** [comment]
Where do you get indentation errors, it it is localized, perhaps we can fix at source level, otherwise I'm happy to add you suggestion. I presume this is for the main CMake file.

**Comment by mikkelfj** [comment]
OK, my patience with GCC warnings is limited so I'll disable.

**Comment by mikkelfj** [comment]
Should be fixed on master, please check.
Wonder why this isn't part of pedantic that should already have been disabled on recent GCC.

**Comment by gmolina-a2e** [comment]
It is, thanks. I will close this issue.

**Comment by mikkelfj** [comment]
I see, pedantic is still on for gcc, next time I'm going to remove pedantic for GCC.

**Comment by amery** [comment]
as the problem is still present, what about including `#pragma GCC diagnostic ignored "-Wmisleading-indentation"` on the generated files?

**Comment by mikkelfj** [comment]
@amery There is distinction between compiling the flatcc tool chain and the runtime. Notably the runtime (library and generated) can be compiled by whatever tool chain the user prefers. I guess this topic only covers the tool chain.

There is a hook for dealing with runtime warnings in the portable library. This is mostly for generic issues that prevent smooth cross platform behaviour and are therefore always enabled. Others should be dealt with in the users tool chain.

The current situation is a bit special because the warning is actually useful in the general case, but specifically for flatcc generated code, it is not helpful. Therefore we cannot or should not inject the warning at the portable layer because the portable library is not flatcc specific.

I have not fully investigated, but I think can conditionally disable the the warning in pdiagnostic.h which is included in all generated files. Then set a flag in flatcc specific include files to enable the warning in this context.

Would you be willing to look into this?

Here the warning can be added in either pwarnings or probably better pdiagnostic.h, guarded by a PDIAGNOSTIC flag:

https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/portable/pwarnings.h
https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/portable/pdiagnostic.h
https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/portable/pdiagnostic_push.h (and pop)

I think the PDIAGNOSTIC enabled warning could then be enabled with a define in 
https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/flatcc_flatbuffers.h
or
https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/flatcc_rtconfig.h

**Comment by ndjhartman** [comment]
This issue has been closed, was this fixed in a later version of flatcc? Either by simply adding a newline in the auto generated code, or disabling the warning with a push/pragma/push?

**Comment by mikkelfj** [comment]
@ndjhartman Please explain your problem more clearly. I assume you that flatbuffers union break for you with -Werror.

The issue with indentation is not limited to any feature but to all generated code, as a rule.
It is not a fixable problem. The flatcc code generator produces large amounts of dense code that is intended for macro expansion not for human consumption. Other flatcc code should be properly indented, and generally is.

You mention pragma push/pop:
I already cover this in my above comment, but there is possibly room for improvement if someone wants to step up.

Historically there are three systems to deal with this:
- the CMake build which is not necessarily what users use, but it tells which warnings are considered necessary. It also deals with warnigns that cannot be handled in source code, notably some MSVC warnings.
- pwarnings.h : here are some warnings that universally break standard C, this is mosly related to old MSVC compilers, afair.
- pdiagnostic_push/pop.h headres. These are included in all generated code. Here the most important compiler specific differences are handled, but handling all compiler variants get complicated fast, just look at CMakeLists.txt

That said, flatcc has always aimed for -Werror with as high a warning level as pratically possible. Because gcc has become overly aggressive, the level of max  warning support for that compiler has been lowered, as it kept breaking things unnecessarily just randomly taking up time to fix nothing, and worse, breaking portability of code. You can again see this in CMakeLists.txt and comments.

So, is it possible to move some of these warning disablers from CMakeLists.txt into pdiagnostics? Yes likely, but we cannot deal with all possible combinations there. If you are willing to put in the effort, and test widely, there is opening here.

See my previous comment where I link these files.

Can we add it to pwarnings.h? No. We want identation warnings in general, and the portable sub library is not flatcc specific, it only disables hostile warnings while pdiagnostics handle cases where flatcc might not adhere to otherwise reasonable warnings for one reason or another.

Can we just use CMakeLists.txt: not really, because users have different builds.

So there isn't a general solution, as there never is with complex software infrastructure.

But the solution is not to modify the flatcc code generator as per earlier comments.

**Comment by mikkelfj** [comment]
@ndjhartman 
I should have added the commit earlier on:
https://github.com/dvidelabs/flatcc/commit/f8c4140dd9dde61c86db751f6002def78754fced

https://github.com/dvidelabs/flatcc/blob/f8c4140dd9dde61c86db751f6002def78754fced/CMakeLists.txt#L228-L231

**Comment by ndjhartman** [comment]
Thanks @mikkelfj. I do see this check present in the CMakeLists.txt. I haven't had time to debug this specifically, but I'm wondering if it's something to do with using compiling with ARM GCC.
